### ISSUE TITLE
Error when making request with no auth

### ISSUE THREAD

**Issue by 0xMimir** [halcyonnouveau/roux#65]
When running request with no auth like fetching subreddit info:
```rust
#[tokio::main]
async fn main() {
    let reddit = roux::Subreddit::new("bitcoin");

    println!("{:#?}", reddit.about().await)
}
```
Output gives:
```
Err(
    Network(
        reqwest::Error {
            kind: Decode,
            source: Error("expected value", line: 1, column: 1),
        },
    ),
)
```

When running test 2 out of 5 tests fail:
```
running 5 tests
test util::option::tests::test_build_url_after ... ok
test util::option::tests::test_build_url_count ... ok
test util::option::tests::test_build_url_before ... ok
test models::user::tests::test_no_auth ... FAILED
test models::subreddit::tests::test_no_auth ... FAILED

failures:

---- models::user::tests::test_no_auth stdout ----
thread 'models::user::tests::test_no_auth' panicked at 'assertion failed: overview.is_ok()', src/models/user/mod.rs:135:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

---- models::subreddit::tests::test_no_auth stdout ----
thread 'models::subreddit::tests::test_no_auth' panicked at 'assertion failed: hot.is_ok()', src/models/subreddit/mod.rs:303:9


failures:
    models::subreddit::tests::test_no_auth
    models::user::tests::test_no_auth

test result: FAILED. 3 passed; 2 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.33s

error: test failed, to rerun pass `--lib`
```

**Comment by beanpuppy** [comment]
thanks for fixing that, seems like something change recently
